AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'

require:
  - rubocop-capybara

plugins:
  - rubocop-rails
  - rubocop-rspec

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 198

Rails/StrongParametersExpect:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
